
#define PACKET_LENGTH   801
#define PACKET_INDEX_BRIGHTNESS 0
#define PACKET_INDEX_PANEL0     1

#define MAXIMUM_PANELSIZE 5
#define PANEL_WIDTH 32
#define PANEL_HEIGHT 40

#define LED_DIAMETER 8
#define LED_DISTANCE (LED_DIAMETER + 3)

#define DEFAULT_WIDTH   (LED_DISTANCE * MAXIMUM_PANELSIZE * PANEL_WIDTH)
#define DEFAULT_HEIGHT  (LED_DISTANCE * PANEL_HEIGHT)
